"""
QA Test Suite for Admin Resources & Uploads
Verifies:
1. Admin Login
2. File Upload (PDF/Image)
3. Material Creation (with file size)
4. Material Listing (verifying persistence)
"""
import asyncio
import httpx
import os
import uuid

BASE_URL = "http://localhost:5000/api"
ADMIN_USER = "rshermans"
ADMIN_PASS = "TRUEcheck@2025"

class Colors:
    GREEN = '\033[92m'
    RED = '\033[91m'
    END = '\033[0m'

async def run_test():
    print(f"🚀 Starting QA for Admin Resources...")
    
    async with httpx.AsyncClient(timeout=30.0) as client:
        # 1. Login
        print("🔹 Testing Auth...")
        try:
            resp = await client.post(f"{BASE_URL}/auth/login", json={"username": ADMIN_USER, "password": ADMIN_PASS})
            if resp.status_code != 200:
                print(f"{Colors.RED}❌ Login Failed: {resp.status_code}{Colors.END}")
                return
            token = resp.json().get("access_token")
            headers = {"Authorization": f"Bearer {token}"}
            print(f"{Colors.GREEN}✅ Login Successful{Colors.END}")
        except Exception as e:
            print(f"{Colors.RED}❌ Login Exception: {e}{Colors.END}")
            return

        # 2. Upload File
        print("🔹 Testing File Upload...")
        dummy_filename = f"qa_test_{uuid.uuid4().hex[:8]}.pdf"
        with open(dummy_filename, "wb") as f:
            f.write(b"%PDF-1.4 dummy content check " * 50)
        
        file_url = None
        file_size = None
        
        try:
            with open(dummy_filename, "rb") as f:
                resp = await client.post(
                    f"{BASE_URL}/upload/?type=pdf", 
                    headers=headers, 
                    files={"file": (dummy_filename, f, "application/pdf")}
                )
            
            if resp.status_code == 200:
                data = resp.json()
                file_url = data["url"]
                file_size = data["size"]
                print(f"{Colors.GREEN}✅ Upload Verified: {file_url} ({file_size}){Colors.END}")
            else:
                print(f"{Colors.RED}❌ Upload Failed: {resp.status_code} - {resp.text}{Colors.END}")
        except Exception as e:
            print(f"{Colors.RED}❌ Upload Exception: {e}{Colors.END}")
        finally:
            if os.path.exists(dummy_filename):
                os.remove(dummy_filename)

        if not file_url:
            return

        # 3. Create Material
        print("🔹 Testing Create Material...")
        try:
            mat_data = {
                "title": f"QA Material {uuid.uuid4().hex[:4]}",
                "type": "pdf",
                "url": file_url,
                "file_size": file_size,
                "description": "Auto-generated by QA"
            }
            resp = await client.post(f"{BASE_URL}/admin/materials", headers=headers, json=mat_data)
            if resp.status_code == 200:
                mat = resp.json()
                print(f"{Colors.GREEN}✅ Material Created: ID {mat['id']}{Colors.END}")
            else:
                print(f"{Colors.RED}❌ Create Material Failed: {resp.status_code} - {resp.text}{Colors.END}")
                return
        except Exception as e:
             print(f"{Colors.RED}❌ Create Material Exception: {e}{Colors.END}")
             return

        # 4. List Materials
        print("🔹 Testing List Materials...")
        try:
            resp = await client.get(f"{BASE_URL}/admin/materials", headers=headers)
            if resp.status_code == 200:
                materials = resp.json()
                # Find our material
                found = next((m for m in materials if m["url"] == file_url), None)
                if found and found.get("file_size") == file_size:
                    print(f"{Colors.GREEN}✅ Material Found in List with correct Size: {found['file_size']}{Colors.END}")
                else:
                    print(f"{Colors.RED}❌ Material Verification Failed: Not found or size mismatch{Colors.END}")
            else:
                 print(f"{Colors.RED}❌ List Materials Failed: {resp.status_code}{Colors.END}")
        except Exception as e:
             print(f"{Colors.RED}❌ List Materials Exception: {e}{Colors.END}")

if __name__ == "__main__":
    asyncio.run(run_test())
